Test suite
ezasm-org/rezasm pull request #102
Opened 2024-08-02 18:31 UTC by AleksBekker

Some of the Rust code (especially surrounding the test suite) had issues, so I moved around the tests and fixed these issues.

Along the way, I fixed #100 (# character in a string/character literal started a comment), and a few of the tests that were failing. Now, running `cargo test --workspace` executes these tests (successfully, as of the time this PR was opened).

2024-08-06 01:19 UTC, TrevorBrunette requested changes

2024-08-06 01:19 UTC, TrevorBrunette commented on rezasm-source/rezasm-core/src/instructions/implementation/mod.rs
> +    // Moved from Trevor's test in tests/core.rs
Remove

2024-08-06 01:19 UTC, TrevorBrunette commented on rezasm-source/rezasm-core/src/instructions/implementation/mod.rs
> +    // Moved from Trevor's test in tests/core.rs
Create issue for this please and remove comment.

2024-08-06 01:19 UTC, TrevorBrunette commented on rezasm-source/rezasm-core/src/instructions/implementation/mod.rs
> +        // FIXME: need to change seek integers due to added comments in the file
Create issue for this please and remove comment

2024-08-09 18:25 UTC, AleksBekker commented on rezasm-source/rezasm-core/src/simulation/simulator.rs
> +    // Moved from Trevor's test in tests/core.rs
Will do

2024-08-09 18:25 UTC, AleksBekker commented on rezasm-source/rezasm-core/src/simulation/simulator.rs
> +    // Moved from Trevor's test in tests/core.rs
Done

2024-08-09 18:25 UTC, AleksBekker commented on rezasm-source/rezasm-core/src/simulation/memory.rs
> +    // Moved from Trevor's test in tests/core.rs
Done

2024-08-09 18:34 UTC, AleksBekker commented
Now closes #105 @TrevorBrunette @WyattRoss

2024-09-10 18:45 UTC, TrevorBrunette approved these changes

2024-09-10 18:48 UTC, merged