File io utility
ezasm-org/rezasm pull request #30
Opened 2023-09-29 21:17 UTC by michaelni678

added rezasm file struct
seek and peek, get bytes, etc
simple tests for all of those

2023-10-03 20:07 UTC, michaelni678 commented
Closes #10

2023-10-06 20:26 UTC, WyattRoss requested changes
See comments.

2023-10-06 20:26 UTC, WyattRoss commented on rezasm-source/rezasm-core/src/util/error.rs
> +    #[error("io failure")]
Output the string for more detail

2023-10-06 20:26 UTC, WyattRoss commented on rezasm-source/rezasm-core/src/util/error.rs
> +    #[error("directory does not exist")]
Unused: remove?

2023-10-06 20:26 UTC, WyattRoss commented on rezasm-app/rezasm-cli/src/main.rs
> +    assert_eq!(fs::metadata(path).is_err(), true);
Platform specific & unnecessary. Remove

2023-10-06 20:26 UTC, WyattRoss commented on rezasm-source/rezasm-core/src/util/io.rs
> +    pub fn prev(&mut self) -> Option<u8> {
check to see if cursor is already 0

2023-10-10 20:31 UTC, merged